# Generated by Django 3.2.3 on 2021-05-23 12:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(default=uuid.UUID('efd053f8-3bc5-4851-b7d2-4bacd4e9667e'), max_length=255)),
                ('given_name', models.TextField(default='Poolguy Device', max_length=255)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DeviceMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature_value', models.FloatField(default=0.0)),
                ('battery_level', models.IntegerField(default=0)),
                ('unit', models.CharField(choices=[('C', 'Celcius'), ('F', 'Fahrenheit')], default='F', max_length=255)),
                ('device', models.ManyToManyField(to='api.Device')),
            ],
        ),
    ]
