# Generated by Django 3.2.3 on 2021-05-23 13:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='device_id',
            field=models.CharField(default=uuid.UUID('137d1775-9f14-4633-bf16-b873d197c59b'), max_length=255),
        ),
        migrations.AlterField(
            model_name='devicemessage',
            name='unit',
            field=models.CharField(default='C', max_length=255),
        ),
    ]
